### ISSUE TITLE
doesn't seem to work

### ISSUE THREAD

**Issue by johndpope** [XCodeBazelize/Bazelize#23]
steps

I clone repo 
git clone https://github.com/Flight-School/AnyCodable

(base) ➜  AnyCodable git:(master) ✗ bazelize --project AnyCodable.xcodeproj
Error: The folder “BUILD” doesn’t exist.

I create a folder BUILD / and or file - doesn't work.

<img width="671" alt="Screen Shot 2022-09-03 at 5 21 34 pm" src="https://user-images.githubusercontent.com/289994/188260513-6b17b664-eb97-400d-a55a-2e1502842a17.png">

**Comment by johndpope** [comment]
I upgraded to this branch 
mint install XCodeBazelize/Bazelize@yume190/plist

and got further...

🌱 Linked bazelize yume190/plist to /Users/johndpope/.mint/bin, replacing version 0.0.2
(base) ➜  AnyCodable git:(master) ✗ bazelize --project AnyCodable.xcodeproj
Create /Users/johndpope/Documents/gitWorkspace/supabase-swift/Sources/AnyCodable/WORKSPACE
Create /Users/johndpope/Documents/gitWorkspace/supabase-swift/Sources/AnyCodable/BUILD
Create /Users/johndpope/Documents/gitWorkspace/supabase-swift/Sources/AnyCodable/.bazelrc

Create /Users/johndpope/Documents/gitWorkspace/supabase-swift/Sources/AnyCodable/AnyCodablePackageDescription/BUILD
Name: AnyCodableTests
Type: com.apple.product-type.bundle.unit-test not gen
Create /Users/johndpope/Documents/gitWorkspace/supabase-swift/Sources/AnyCodable/AnyCodableTests/BUILD
Create /Users/johndpope/Documents/gitWorkspace/supabase-swift/Sources/AnyCodable/AnyCodable/BUILD

**Comment by johndpope** [comment]
fyi - getting some mileage with this + 
https://github.com/unsignedapps/swift-create-xcframework


the anycodable problem I solved by renaming framework
https://github.com/unsignedapps/swift-create-xcframework/issues/80

**Comment by yume190** [comment]
@johndpope. Thx for your reporting.

It still needs a patch for the current implementation.

```bash
mint install XCodeBazelize/Bazelize@main
git clone https://github.com/Flight-School/AnyCodable
cd AnyCodable
bazelize --project AnyCodable.xcodeproj
bazel build AnyCodable 

ERROR: /Users/yume/Desktop/AnyCodable/AnyCodable/BUILD:4:14: no such target '//:Sources/AnyCodable/AnyCodable.swift': target 'Sources/AnyCodable/AnyCodable.swift' not declared in package ''; however, a source file of this name exists.  (Perhaps add 'exports_files(["Sources/AnyCodable/AnyCodable.swift"])' to /BUILD?) defined by /Users/yume/Desktop/AnyCodable/BUILD and referenced by '//AnyCodable:AnyCodable_swift'
ERROR: /Users/yume/Desktop/AnyCodable/AnyCodable/BUILD:4:14: no such target '//:Sources/AnyCodable/AnyDecodable.swift': target 'Sources/AnyCodable/AnyDecodable.swift' not declared in package ''; however, a source file of this name exists.  (Perhaps add 'exports_files(["Sources/AnyCodable/AnyDecodable.swift"])' to /BUILD?) defined by /Users/yume/Desktop/AnyCodable/BUILD and referenced by '//AnyCodable:AnyCodable_swift'
ERROR: /Users/yume/Desktop/AnyCodable/AnyCodable/BUILD:4:14: no such target '//:Sources/AnyCodable/AnyEncodable.swift': target 'Sources/AnyCodable/AnyEncodable.swift' not declared in package ''; however, a source file of this name exists.  (Perhaps add 'exports_files(["Sources/AnyCodable/AnyEncodable.swift"])' to /BUILD?) defined by /Users/yume/Desktop/AnyCodable/BUILD and referenced by '//AnyCodable:AnyCodable_swift'
```

## Patch `BUILD`

```diff
+ exports_files([
+     "Sources/AnyCodable/AnyCodable.swift",
+     "Sources/AnyCodable/AnyDecodable.swift",
+     "Sources/AnyCodable/AnyEncodable.swift",
+ ])
```

![image](https://user-images.githubusercontent.com/3355810/188413945-829d9433-8974-48be-82e0-24b6e7fa5f89.png)
